project_id = "knybxihimqrqwzkdeaio"

[functions.ai-symptom-checker]
verify_jwt = false

[functions.ai-soap-note]
verify_jwt = false

[functions.ai-translate]
verify_jwt = false

[functions.send-appointment-reminder]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.create-video-room]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.instant-connect]
verify_jwt = false

[functions.oauth-connect]
verify_jwt = true

[functions.ai-financial-analysis]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.submit-claim]
verify_jwt = true

[functions.check-eligibility]
verify_jwt = true

[functions.match-waitlist]
verify_jwt = false

[functions.sync-calendar]
verify_jwt = true

[functions.send-prescription]
verify_jwt = true

[functions.submit-lab-order]
verify_jwt = true

[functions.sync-rpm-devices]
verify_jwt = true

[functions.oauth-rpm-connect]
verify_jwt = true

[functions.moderate-review]
verify_jwt = true

[functions.send-notification]
verify_jwt = false

[functions.insurance-reminder]
verify_jwt = false
