project_id = "knybxihimqrqwzkdeaio"

[functions.send-email]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.create-video-room]
verify_jwt = true

[functions.create-payment]
verify_jwt = true
