project_id = "knybxihimqrqwzkdeaio"

[functions.ai-symptom-checker]
verify_jwt = false

[functions.ai-soap-note]
verify_jwt = false

[functions.ai-translate]
verify_jwt = false

[functions.send-appointment-reminder]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.create-video-room]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.instant-connect]
verify_jwt = false

[functions.oauth-connect]
verify_jwt = true

[functions.ai-financial-analysis]
verify_jwt = true
