project_id = "knybxihimqrqwzkdeaio"

[functions.send-email]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.create-video-room]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.ai-symptom-checker]
verify_jwt = true

[functions.ai-soap-note]
verify_jwt = true
