project_id = "knybxihimqrqwzkdeaio"

[functions.send-notification-email]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.create-video-token]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
