project_id = "knybxihimqrqwzkdeaio"

[functions.blockchain-verify-record]
verify_jwt = true

[functions.voice-command-history]
verify_jwt = true

[functions.voice-multi-language-processor]
verify_jwt = true

[functions.pharmacy-inventory-optimization]
verify_jwt = true

[functions.multi-tenant-billing-reconciliation]
verify_jwt = true

[functions.revenue-prediction-ml]
verify_jwt = true

[functions.patient-churn-prediction]
verify_jwt = true

[functions.epic-fhir-sync]
verify_jwt = true

[functions.enterprise-sso]
verify_jwt = true

[functions.multi-clinic-routing]
verify_jwt = true

[functions.rpm-compliance-tracking]
verify_jwt = true

[functions.predictive-readmission]
verify_jwt = true

[functions.ai-schedule-optimizer]
verify_jwt = true

[functions.patient-routing-engine]
verify_jwt = true

[functions.queue-prioritization-ai]
verify_jwt = true

[functions.earnings-analytics]
verify_jwt = true

[functions.clinic-performance-metrics]
verify_jwt = true

[functions.staff-utilization-tracker]
verify_jwt = true

[functions.voice-to-prescription]
verify_jwt = true

[functions.voice-to-icd10]
verify_jwt = true

[functions.voice-quality-check]
verify_jwt = true

[functions.voice-session-summary]
verify_jwt = true

[functions.voice-command-routing]
verify_jwt = true

[functions.verify-insurance-realtime]
verify_jwt = true

[functions.process-hsa-fsa-payment]
verify_jwt = true

[functions.calculate-fee-split]
verify_jwt = true

[functions.create-affirm-installment]
verify_jwt = true

[functions.create-carecredit-plan]
verify_jwt = true

[functions.subscription-autopay]
verify_jwt = false

[functions.generate-superbill]
verify_jwt = true

[functions.payment-dispute-handler]
verify_jwt = true

[functions.voice-navigation-command]
verify_jwt = true

[functions.voice-to-task]
verify_jwt = true

[functions.ai-care-plan-generator]
verify_jwt = true

[functions.ai-medication-interaction-checker]
verify_jwt = true

[functions.ai-clinical-decision-support]
verify_jwt = true

[functions.ai-lab-result-interpreter]
verify_jwt = true

[functions.ai-radiology-report-analyzer]
verify_jwt = true

[functions.scan-health-card-vision]
verify_jwt = true

[functions.check-drug-interactions]
verify_jwt = true

[functions.calculate-earnings-forecast]
verify_jwt = true

[functions.generate-ans-report]
verify_jwt = true

[functions.generate-hipaa-audit]
verify_jwt = true

[functions.gdpr-data-export]
verify_jwt = true

[functions.ai-icd-suggester]
verify_jwt = true

[functions.import-from-google-maps]
verify_jwt = true

[functions.unified-patient-search]
verify_jwt = true

[functions.voice-to-soap-realtime]
verify_jwt = true

[functions.ai-consultation-assistant]
verify_jwt = true

[functions.clinic-financial-dashboard]
verify_jwt = true

[functions.ai-moderate-content]
verify_jwt = true

[functions.docusign-signature]
verify_jwt = true

[functions.check-insurance-eligibility]
verify_jwt = true

[functions.sync-icd-codes]
verify_jwt = true

[functions.voice-assistant]
verify_jwt = true

[functions.ai-chatbot]
verify_jwt = false

[functions.verify-credentials]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.classify-and-route-message]
verify_jwt = true

[functions.manage-work-queue]
verify_jwt = true

[functions.legal-archive]
verify_jwt = true

[functions.newrelic-monitor]
verify_jwt = false

[functions.moderate-review-ai]
verify_jwt = true

[functions.support-chatbot]
verify_jwt = true

[functions.check-eligibility-ai]
verify_jwt = true

[functions.generate-export]
verify_jwt = true

[functions.ai-symptom-checker]
verify_jwt = false

[functions.ai-symptom-check]
verify_jwt = true

[functions.ai-config-manage]
verify_jwt = true

[functions.ai-source-validate]
verify_jwt = true

[functions.ai-meta-instruction]
verify_jwt = true

[functions.ai-soap-note]
verify_jwt = false

[functions.ai-translate]
verify_jwt = false

[functions.send-appointment-reminder]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.create-video-room]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.instant-connect]
verify_jwt = false

[functions.oauth-connect]
verify_jwt = true

[functions.ai-financial-analysis]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.submit-claim]
verify_jwt = true

[functions.check-eligibility]
verify_jwt = true

[functions.match-waitlist]
verify_jwt = false

[functions.sync-calendar]
verify_jwt = true

[functions.smart-appointment-routing]
verify_jwt = false

[functions.dynamic-pricing-optimizer]
verify_jwt = false

[functions.automated-appointment-reminder]
verify_jwt = false

[functions.no-show-prediction]
verify_jwt = false

[functions.ai-documentation-assistant]
verify_jwt = false

[functions.insurance-verification-ai]
verify_jwt = false

[functions.treatment-outcome-predictor]
verify_jwt = false

[functions.send-prescription]
verify_jwt = true

[functions.submit-lab-order]
verify_jwt = true

[functions.sync-rpm-devices]
verify_jwt = true

[functions.oauth-rpm-connect]
verify_jwt = true

[functions.moderate-review]
verify_jwt = true

[functions.send-notification]
verify_jwt = false

[functions.insurance-reminder]
verify_jwt = false

[functions.elevenlabs-signed-url]
verify_jwt = true

[functions.translate-support]
verify_jwt = false

[functions.notify-verification-reminder]
verify_jwt = false

[functions.notify-procedure-match]
verify_jwt = false

[functions.send-multi-channel-notification]
verify_jwt = false

[functions.route-procedure-question]
verify_jwt = false

[functions.generate-data-summary]
verify_jwt = true

[functions.track-usage]
verify_jwt = true

[functions.notify-price-change]
verify_jwt = false

[functions.epic-fhir-sync]
verify_jwt = true

[functions.enterprise-sso]
verify_jwt = true

[functions.multi-clinic-routing]
verify_jwt = true

[functions.rpm-compliance-tracking]
verify_jwt = true

[functions.predictive-readmission]
verify_jwt = true

[functions.ai-schedule-optimizer]
verify_jwt = true

[functions.patient-routing-engine]
verify_jwt = true

[functions.queue-prioritization-ai]
verify_jwt = true

[functions.earnings-analytics]
verify_jwt = true

[functions.clinic-performance-metrics]
verify_jwt = true

[functions.staff-utilization-tracker]
verify_jwt = true

[functions.check-video-health]
verify_jwt = true

[functions.book-with-hold]
verify_jwt = true

[functions.waitlist-matcher]
verify_jwt = false

[functions.book-appointment-atomic]
verify_jwt = true

[functions.constraint-search]
verify_jwt = false

[functions.calendar-token-refresh]
verify_jwt = false

[functions.connect-triage-to-booking]
verify_jwt = true

[functions.verify-insurance-before-booking]
verify_jwt = true

[functions.sync-shift-to-availability]
verify_jwt = true

[functions.send-whatsapp-message]
verify_jwt = true

[functions.lock-cost-estimate]
verify_jwt = true

[functions.coordinate-group-booking]
verify_jwt = true

[functions.check-compliance-rules]
verify_jwt = true

[functions.warm-search-cache]
verify_jwt = false

[functions.calendar-sync-bidirectional]
verify_jwt = true

[functions.extract-soap-billing-codes]
verify_jwt = true

[functions.ai-moderate-review]
verify_jwt = true

[functions.import-ehr-data]
verify_jwt = true

[functions.map-fhir-resources]
verify_jwt = true

[functions.log-security-event]
verify_jwt = true

[functions.check-rate-limit]
verify_jwt = false

[functions.ai-clinic-triage]
verify_jwt = true

[functions.medical-knowledge-search]
verify_jwt = true

[functions.ai-sandbox-execute]
verify_jwt = true

[functions.ai-source-freshness-check]
verify_jwt = false

[functions.chat-stream]
verify_jwt = true

[functions.generate-blog-content]
verify_jwt = true

[functions.semantic-search]
verify_jwt = true

[functions.generate-embeddings]
verify_jwt = true

[functions.ai-recommend]
verify_jwt = true

[functions.ai-autofill]
verify_jwt = true

[functions.generate-pdf]
verify_jwt = true

[functions.manage-api-keys]
verify_jwt = true

[functions.verify-api-key]
verify_jwt = false

[functions.track-event]
verify_jwt = false

[functions.create-stripe-subscription]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.create-google-business-listing]
verify_jwt = true

[functions.auto-update-specialist-status]
verify_jwt = false

[functions.update-specialist-profile]
verify_jwt = true

[functions.oauth-universal]
verify_jwt = true

[functions.send-whatsapp-business]
verify_jwt = true

[functions.import-from-google-maps]
verify_jwt = true

[functions.smart-specialist-matcher]
verify_jwt = false

[functions.one-tap-reschedule]
verify_jwt = true

[functions.waitlist-auto-insert]
verify_jwt = false

[functions.send-waitlist-notification]
verify_jwt = false

[functions.staff-invitation]
verify_jwt = true

[functions.generate-temp-email]
verify_jwt = true

[functions.qr-profile-export]
verify_jwt = true

[functions.qr-profile-import]
verify_jwt = false

[functions.voice-to-task]
verify_jwt = true

[functions.ai-team-insights]
verify_jwt = true

[functions.payment-per-booking]
verify_jwt = true

[functions.ai-generate-insights]
verify_jwt = false

[functions.health-record-request]
verify_jwt = true

[functions.prescription-external-receive]
verify_jwt = false

[functions.genomic-risk-calculator]
verify_jwt = false

[functions.mental-health-crisis-detector]
verify_jwt = false

[functions.medication-adherence-tracker]
verify_jwt = false

[functions.drug-interaction-checker]
verify_jwt = false

[functions.clinical-trial-enrollment]
verify_jwt = false

[functions.capacity-forecasting-ml]
verify_jwt = false

[functions.hipaa-compliance-validator]
verify_jwt = false
