// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knybxihimqrqwzkdeaio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtueWJ4aWhpbXFycXd6a2RlYWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxODY4MTgsImV4cCI6MjA3NDc2MjgxOH0.Sw-MGFnleR4fH6n-QOjL6Ig1PbtrNPbCYLe0Wn8b_h4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});